//Por Lucas

//CLIENTE
CREATE TABLE Cliente(
	ID_Cliente    INT 		  NOT NULL AUTO_INCREMENT,
	CPF			  CHAR(11)    NOT NULL,
	Telefone_Resi CHAR(08),
	Telefone_Celu CHAR(11),
	Nome		  VARCHAR(45) NOT NULL,
	Email		  VARCHAR(45) NOT NULL,
	Numero		  VARCHAR(04) NOT NULL,
	Rua			  VARCHAR(45) NOT NULL,
	Bairro		  VARCHAR(45) NOT NULL,
	Cidade		  VARCHAR(45) NOT NULL,
	Estado		  VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID_Cliente),
	UNIQUE (CPF)
);

//PRODUTOS
CREATE TABLE Produto(
	COD_Produto INT 		NOT NULL AUTO_INCREMENT,
	Unidade		VARCHAR(10) NOT NULL,
	Unidade_Tp  VARCHAR(02) NOT NULL,
	Preco		FLOAT		NOT NULL,
	Descricao	TINYTEXT	NOT NULL,
	PRIMARY KEY (COD_Produto)
);

//VENDA
CREATE TABLE   Venda(
	COD_Venda  INT   NOT NULL AUTO_INCREMENT, 
	ID_Cliente INT   NOT NULL,
	Data	   DATE  NOT NULL,
	Preco	   FLOAT NOT NULL,
	PRIMARY KEY (COD_Venda),
	FOREIGN KEY (ID_Cliente)   REFERENCES Cliente(ID_Cliente)
);

//ITENS_VENDA
CREATE TABLE Item_Venda(
	ID_Item_Venda INT   NOT NULL AUTO_INCREMENT,
	COD_Venda     INT   NOT NULL,
	COD_Produto   INT   NOT NULL,
	PRIMARY KEY (ID_Item_Venda),
	FOREIGN KEY (COD_Venda)   REFERENCES Venda(COD_Venda),
	FOREIGN KEY (COD_Produto) REFERENCES Produto(COD_Produto)
);